---
- name: "Ensuring required variables are defined"
  ansible.builtin.assert:
    that:
      - fw_ipsets is defined
    fail_msg: "All tests did not pass"

- name: "Collecting ipsets"
  ansible.builtin.command: >
    firewall-cmd
    --get-ipsets
    --permanent
  register: ipsets
  changed_when: false

- name: "Ensuring ipset is present"
  ansible.builtin.command: >
    firewall-cmd
    --new-ipset="{{ item.name }}"
    --permanent
    --type="{{ fw_ipset_type }}"
  loop: "{{ fw_ipsets }}"
  when: "item.name not in ipsets.stdout.split()"
  register: my_output
  changed_when: my_output.rc != 0

- name: "Ensuring ipset description is set if available"
  ansible.builtin.command: >
    firewall-cmd
    --ipset="{{ item.name }}"
    --permanent
    --set-description="{{ item.description }}"
  loop: "{{ fw_ipsets }}"
  when: "item.name in ipsets.stdout.split() and item.description is defined"
  register: my_output
  changed_when: my_output.rc != 0
