---
- name: "Ensuring required variables are defined"
  ansible.builtin.assert:
    that:
      - fw_ipsets is defined
    fail_msg: "All tests did not pass"

- name: "Ensuring inbound port is closed for ipset"
  ansible.builtin.command: >
    firewall-cmd
    --permanent
    --remove-rich-rule="rule source ipset='{{ item.0.name }}' port port={{ item.1 | split('/') | first }} protocol={{ item.1 | split('/') | last }} accept"
    --zone="{{ fw_zone }}"
  loop: "{{ fw_ipsets | selectattr('in.ports', 'defined') | subelements('in.ports') }}"
  register: my_output
  changed_when: my_output.rc != 0

- name: "Ensuring outbound port is closed for ipset"
  ansible.builtin.command: >
    firewall-cmd
    --permanent
    --remove-rich-rule="rule destination ipset='{{ item.0.name }}' port port={{ item.1 | split('/') | first }} protocol={{ item.1 | split('/') | last }} accept"
    --zone="{{ fw_zone }}"
  loop: "{{ fw_ipsets | selectattr('out.ports', 'defined') | subelements('out.ports') }}"
  register: my_output
  changed_when: my_output.rc != 0
