---
- name: "Ensuring required variables are defined"
  ansible.builtin.assert:
    that:
      - fw_ipsets is defined
    fail_msg: "All tests did not pass"

- name: "Collecting ipsets"
  ansible.builtin.command: >
    firewall-cmd --get-ipsets
  register: ipsets
  changed_when: false

- name: "Ensuring ip is absent in ipset"
  ansible.builtin.command: >
    firewall-cmd --permanent --ipset="{{ item.0.name }}" --remove-entry="{{ item.1 }}"
  loop: "{{ fw_ipsets | subelements('entries') }}"
  when: "item.0.name in ipsets.stdout.split()"
  register: my_output
  changed_when: my_output.rc != 0
