---
- name: "Ensure fw_ipsets is defined"
  ansible.builtin.asset:
    that:
      - fw_ipsets is defined
    fail_msg: "fw_ipsets is not defined"

- name: "Collecting ipsets"
  ansible.builtin.command: >
    firewall-cmd --get-ipsets
  register: ipsets

- name: "Ensuring ipset is present"
  ansible.builtin.command: >
    firewall-cmd --permanent --new-ipset="{{ item.name }}" --type="{{ fw_ipset_type }}"
  loop: "{{ fw_ipsets }}"
  when: "item.name not in ipsets.stdout.split()"
